openssl: fix EVP_ENCODE_CTX_(new|free)
Add both the missing header file, and an implementation for OpenSSL 1.0.2
versions.

Fixes errors like:

lib/tpm2_convert.c:655:5: error: implicit declaration of function 'EVP_ENCODE_CTX_new' [-Werror=implicit-function-declaration]
     EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
     ^
lib/tpm2_convert.c:655:27: error: initialization makes pointer from integer without a cast [-Werror]
     EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();

lib/tpm2_convert.c:661:9: error: implicit declaration of function 'EVP_ENCODE_CTX_free' [-Werror=implicit-function-declaration]
         EVP_ENCODE_CTX_free(ctx);

Signed-off-by: William Roberts <william.c.roberts@intel.com>