tools/tpm2_nvincrement: mark ectx as unused for check_options()
The unused parameter leads to a compiler warning/error with GCC 11.1.0:

tools/tpm2_nvincrement.c: In function ‘check_options’:
tools/tpm2_nvincrement.c:169:44: error: unused parameter ‘ectx’ [-Werror=unused-parameter]
  169 | static tool_rc check_options(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
      |                              ~~~~~~~~~~~~~~^~~~

Signed-off-by: Jonas Witschel <git@diabonas.de>