tpm2_nv_util: inline tpm2_util_nv_read_public
inline tpm2_util_nv_read_public() to avoid a dependency
on TSS which was causing:

lib/tpm2_nv_util.c:486: undefined reference to `Tss2_Sys_NV_ReadPublic'

Signed-off-by: William Roberts <william.c.roberts@intel.com>