tpm2_getmanufec: fix options character string
Some of the tools option don't require an argument, but the optstring is
wrongly assuming that all the options need one. This leads to following:

$ tpm2_getmanufec -O
tpm2_getmanufec: option requires an argument -- 'O'
ERROR: Unknown Argument: O

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>