tpm2_import: Allow to build with OpenSSL 1.1.0
Since OpenSSL version 1.1.0, the RSA structure (struct rsa_st) is opaque
to programs (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).

So the structure members can't be accessed directly and instead helpers
functions should be used.

Because the API changes, building tpm2-tools with OpenSSL 1.1.x leads to
the following compile error:

CC       tools/tpm2_import.o
In file included from tools/tpm2_import.c:39:
tools/tpm2_import.c: In function ‘load_rsa_key’:
tools/tpm2_import.c:684:36: error: dereferencing pointer to incomplete type ‘RSA’ {aka ‘struct rsa_st’}
     int priv_bytes = BN_num_bytes(k->p);
                                    ^~
make: *** [Makefile:1982: tools/tpm2_import.o] Error 1

Fixes: d53fcf9b9264 ("tpm2_import: import from pem file")
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>