Removed unused function 'fixup_name'
lib/tpm2_options.c:114:27: error:
unused function 'fixup_name' [-Werror,-Wunused-function]

Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>