tpm2_getmanufec: fix endorsement hierarchy authentication
Endorsement hierarchy authentication is broken since the HMAC size was not
correctly set. This leads to the following error:

$ tpm2_takeownership -e epass -o opass
$ $ tpm2_getmanufec -S https://ekop.intel.com/ekcertservice/ -H 0x81000000 \
  -E ECcert2.bin -f ek.bin -o opass -e epass
ERROR: EvictControl:Make EK persistent Error. TPM Error:0x9a2

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>