tpm2_alg_util: add definitions for algorithms not defined in tpm2-tss 1.x
Some algorithms are not defined in the tpm2-tss 1.x branch, so this causes
the following build error when building the tpm2-tools against that branch:

lib/tpm2_alg_util.c: In function ‘tpm2_alg_util_for_each_alg’:
lib/tpm2_alg_util.c:74:34: error: ‘TPM_ALG_ECMQV’ undeclared (first use in this function); did you mean ‘TPM_ALG_ECB’?
         { .name = "ecmqv", .id = TPM_ALG_ECMQV },
                                  ^~~~~~~~~~~~~
                                  TPM_ALG_ECB
lib/tpm2_alg_util.c:74:34: note: each undeclared identifier is reported only once for each function it appears in
lib/tpm2_alg_util.c:76:33: error: ‘TPM_ALG_KDF2’ undeclared (first use in this function); did you mean ‘TPMI_ALG_KDF’?
         { .name = "kdf2", .id = TPM_ALG_KDF2 },
                                 ^~~~~~~~~~~~
                                 TPMI_ALG_KDF
lib/tpm2_alg_util.c:80:37: error: ‘TPM_ALG_CAMELLIA’ undeclared (first use in this function); did you mean ‘ALG_CAMELLIA’?
         { .name = "camellia", .id = TPM_ALG_CAMELLIA },
                                     ^~~~~~~~~~~~~~~~
                                     ALG_CAMELLIA
lib/tpm2_alg_util.c:81:37: error: ‘TPM_ALG_SHA3_256’ undeclared (first use in this function); did you mean ‘TPM_ALG_SHA256’?
         { .name = "sha3_256", .id = TPM_ALG_SHA3_256 },
                                     ^~~~~~~~~~~~~~~~
                                     TPM_ALG_SHA256
lib/tpm2_alg_util.c:82:37: error: ‘TPM_ALG_SHA3_384’ undeclared (first use in this function); did you mean ‘TPM_ALG_SHA384’?
         { .name = "sha3_384", .id = TPM_ALG_SHA3_384 },
                                     ^~~~~~~~~~~~~~~~
                                     TPM_ALG_SHA384
lib/tpm2_alg_util.c:83:37: error: ‘TPM_ALG_SHA3_512’ undeclared (first use in this function); did you mean ‘TPM_ALG_SHA512’?
         { .name = "sha3_512", .id = TPM_ALG_SHA3_512 },
                                     ^~~~~~~~~~~~~~~~
                                     TPM_ALG_SHA512
make: *** [Makefile:1871: lib/tpm2_alg_util.o] Error 1

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>