tools/tpm2_checkquote: fix missing initializer
Fixes:
tools/misc/tpm2_checkquote.c:466:9: error: missing initializer for field 'data' of 'tpm2_eventlog_context' [-Werror=missing-field-initializers]
         tpm2_eventlog_context eventlog_ctx = {};

Signed-off-by: William Roberts <william.c.roberts@intel.com>