lib/tpm2_util.c fix compile error on raspian
On raspian 11 with gcc 10.2.1 the following error occurred:

 error: format ‘%lu’ expects argument of type ‘long unsigned int’,
 but argument 2 has type ‘UINT64’

lu was replaced with PRIu64.

Signed-off-by: Juergen Repp <juergen_repp@web.de>