test: fix compilation
With gcc v7.3.1 test_tpm2_alg_util.c fails with:
In file included from test/unit/test_tpm2_alg_util.c:33:0:
test/unit/test_tpm2_alg_util.c: In function ‘test_pcr_parse_digest_list_compound’:
test/unit/test_tpm2_alg_util.c:349:78: error: array subscript is above array bounds [-Werror=array-bounds]
             fail_msg("Missing algorithm test for: %u", dspec->digests.digests[i].hashAlg);
                                                        ~~~~~~~~~~~~~~~~~~~~~~^~~

Fix this by explicitly checking the array bounds.

Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>