test: fix missing-braces error
test/unit/test_options.c:64:54: error: suggest braces around
initialization of subobject [-Werror,-Wmissing-braces]
static TSS2_TCTI_CONTEXT_COMMON_V2 tcti_instance = { 0, };
Since unitialized global/static variables are automatically
zeroed we can just remove the initialization.

Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>