tpm2_import: Fix build error due missing break in a case statement
This commit fixes the following GCC warning that leads to a compile error:

  CC       tools/tpm2_import.o
tools/tpm2_import.c: In function ‘on_option’:
tools/tpm2_import.c:590:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         switch(ctx.key_type) {
         ^~~~~~
tools/tpm2_import.c:602:5: note: here
     case 'K':
     ^~~~
cc1: all warnings being treated as errors

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>