tpm2_import: fix build error with OpenSSL 1.1.x
Since OpenSSL version 1.1.0, the RSA structure (struct rsa_st) is opaque
to programs (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).

So the structure members can't be accessed directly and instead helpers
functions should be used.

Because the API changes, building tpm2-tools with OpenSSL 1.1.x leads to
the following compile error:

tools/tpm2_import.c:99:11: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     if ((r->n == NULL && n == NULL) || (r->e == NULL && e == NULL)) {
           ^~

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>