kdfa: allow to build with OpenSSL 1.1.x
OpenSSL version 1.1 has some API changes that makes many data structures
to be opaque as explained in [0]. The changes causes the following build
error when using OpenSSL 1.1.x libs:

lib/tpm_kdfa.c: In function ‘tpm_kdfa’:
lib/tpm_kdfa.c:93:14: error: storage size of ‘ctx’ isn’t known
     HMAC_CTX ctx;
              ^~~
lib/tpm_kdfa.c:94:5: error: implicit declaration of function ‘HMAC_CTX_init’; did you mean ‘HMAC_CTX_new’? [-Werror=implicit-function-declaration]
     HMAC_CTX_init(&ctx);
     ^~~~~~~~~~~~~
     HMAC_CTX_new
lib/tpm_kdfa.c:150:5: error: implicit declaration of function ‘HMAC_CTX_cleanup’; did you mean ‘HMAC_CTX_get_md’? [-Werror=implicit-function-declaration]
     HMAC_CTX_cleanup(&ctx);
     ^~~~~~~~~~~~~~~~

[0]: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>