Use %u instead of %lu format specifier for uint16
max_data_size is uint16, therefore GCC 11.1.0 gives warnings/errors like

./lib/tpm2_nv_util.h: In function ‘tpm2_util_nv_read’:
./lib/tpm2_nv_util.h:238:17: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘int’ [-Werror=format=]
  238 |         LOG_ERR("Cannot continue as the policy auth session must be "
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
  241 |                 "read size of %lu", max_data_size, max_data_size);
      |                                     ~~~~~~~~~~~~~
      |                                     |
      |                                     int

Fixes: 6468c73d7e8fe5d138f54a6d49ef9e0c28deabe7 ("tools/tpm2_nvread: fix reads > TPM2_PT_NV_BUFFER_MAX with policy session")
Fixes: 4d7456dee8111190faf1d5c9d91b0602d653a342 ("tools/tpm2_nvwrite: fix writes > TPM2_PT_NV_BUFFER_MAX with policyauth")

Signed-off-by: Jonas Witschel <git@diabonas.de>