tpm2_createek: Correct man page example
The example
 tpm2_createek -G rsa -u ek.pub
from 'man tpm2_createek' misses to provide '-c'.

It thus fails with
 ERROR: Expected option -c

According to tools/tpm2_createek.c:441, the option must be present in
any case. Adjust the man page example accordingly.

Signed-off-by: Tobias Deiminger <tdmg@linutronix.de>