tpm2_sign: fix option error output
The error:
ERROR: Expected options (k or c) and (m or D) and s

Is both incorrect and confusing. Correct the "k" output, as "k"
is no longer supported and output them one at a time so the user
doesn't need to figure out what they were missing.

Output after:
ERROR: Expected option c
ERROR: Expected options m or D
ERROR: Expected option s

With the message line going away when the option is specified.

Signed-off-by: William Roberts <william.c.roberts@intel.com>