readthedocs: Add markdown to requirement file.
The latest markdown version did produce the error:
missing 1 required positional argument: 'md_globals'
Markdown<3.2 was added to the requirement file.

Signed-off-by: Juergen Repp <juergen_repp@web.de>