build: use supported comment to suppress GCC7 fallthrough warning
GCC7 warns when a case in a switch statement falls through the next case
block, this leads to the following build error due using -Werror option:

tools/main.c:62:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         fprintf (stderr,
         ^~~~~~~~~~~~~~~~
                  "failed to load manpage, check your environment / PATH\n");
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/main.c:65:5: note: here
     case 2:
     ^~~~
cc1: all warnings being treated as errors

The commit 054b1f3e85a7 ("main: explicitly state fall through in switch
is expected") added a comment to avoid some tools to complain about it,
but let's change to one that matches the regular expression defined by
GCC's -Wimplicit-fallthrough=3 (the default when the option is enabled).

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>