liberror: introduce a new error decoding library
Introduce an error decoding interface similair to C's
strerror(3).

Add unit tests.

The tools will be consuming this for the 4.0 release under
ticket #769:
  - https://github.com/tpm2-software/tpm2-tools/issues/769

Signed-off-by: William Roberts <william.c.roberts@intel.com>