man: update TCTI options man according to the new options handling
Commit 1cb24d62d6b ("option fixing: move to single getopt") reworked how
the options are handled by the tools, but it also changed how the TCTI
specific options are passed to the TCTI initialization code.

The man pages were not updated and still list the old way to specify the
TCTI specific options, users reading the man page will face this issue:

$ tpm2_pcrlist -L sha1:7 -T device -d /dev/tpm0
tpm2_pcrlist: invalid option -- 'd'
ERROR: Unknown Argument: d

Update man pages so users know that they instead need to do following:

$ tpm2_pcrlist -L sha1:7 -T device:/dev/tpm0

Bank/Algorithm: sha(0x0004)
PCR_07:6d7206871c9c6f38ad3997baceebee95dadec04d

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>