tpm2-checkqoute: fix wrong format specifier
Fixes this compilation error:
```In file included from tools/misc/tpm2_checkquote.c:12:0:
tools/misc/tpm2_checkquote.c: In function ‘parse_selection_data_from_file’:
tools/misc/tpm2_checkquote.c:270:17: error: format ‘%zu’ expects
argument of type ‘size_t’, but argument 6 has type ‘__uint64_t {aka long
long unsigned int}’ [-Werror=format=]
         LOG_ERR("Malformed PCR file, pcr count cannot be greater than
%zu, got: %zu",
```
le64toh always returns an uint64_t, thus %PRIu64

Co-authored-by: Imran Desai <imran.desai@intel.com>
Signed-off-by: Peter Huewe <peter.huewe@infineon.com>