tpm2_createpolicy: fix logic to count set bits on PCR banks
In the evaluate_populate_pcr_digests() function, the number of bits set
for each PCR bank is count to estimate the raw PCR hashes file expected
size. But the logic isn't correct, only the four least significant bits
are taked into account.

So it fails to count as set any PCR id where id % 8 > 3, for example:

$ tpm2_createpolicy -P -L 0x0004:4 -F pcr.bin -f policy.data
ERROR: pcr-input-file filesize does not match pcr set-list
ERROR: Failed parse_policy_type_and_send_command

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>