tools/tpm2_nvreadpublic: mark ectx as unused for check_options()
This leads to the following compiler warning/error:

tools/tpm2_nvreadpublic.c: In function ‘check_options’:
tools/tpm2_nvreadpublic.c:270:44: error: unused parameter ‘ectx’ [-Werror=unused-parameter]
  270 | static tool_rc check_options(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
      |                              ~~~~~~~~~~~~~~^~~~

Signed-off-by: Jonas Witschel <git@diabonas.de>