conversion: fix build error with OpenSSL 1.1.x
Since OpenSSL version 1.1.0, the RSA structure (struct rsa_st) is opaque
to programs (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).

So the structure members can't be accessed directly and instead helpers
functions should be used.

Because the API changes, building tpm2-tools with OpenSSL 1.1.x leads to
the following compile error:

lib/conversion.c: In function ‘tpm2_convert_pubkey_ssl’:
lib/conversion.c:126:16: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     ssl_rsa_key->e = BN_bin2bn((void*)&exponent, sizeof(exponent), NULL);
                ^~
make: *** [Makefile:1842: lib/conversion.o] Error 1

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>