ci: make check TESTS='' with default settings
There was never a make check run with the default configure flags, and
thus we were losing Wall Werror type messages. There was also some
issues in the if gcc check, so correct those too.

See PR as an example:
  - https://github.com/tpm2-software/tpm2-tools/pull/1682

Now we get error:
test/unit/test_options.c:255:26: error: unused parameter 'unused_param' [-Werror=unused-parameter]
 void unused_function(int unused_param) {

Signed-off-by: William Roberts <william.c.roberts@intel.com>