tools/tpm2_nvwrite.c: remove unused "flags" parameter from process_output()
The unused parameter leads to a compiler warning/failure with GCC 11.1.0:

tools/tpm2_nvwrite.c: In function ‘process_output’:
tools/tpm2_nvwrite.c:95:69: error: unused parameter ‘flags’ [-Werror=unused-parameter]
   95 | static tool_rc process_output(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
      |
cc1: all warnings being treated as errors

Fixes: d6a33b02c4515c72bfed09549eb6e6b8d6bcebeb ("tools/tpm2_nvwrite.c: Redo tools layout")
Signed-off-by: Jonas Witschel <git@diabonas.de>