tpm2_getrandom: bound on max hash size
Per 16.1 of:
  - https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf

It is recommended that TPMs bound entropy available to max hash size in
bytes and always make that available. TPMs do not issue an error when
size requested comes up short. Thus add checks for these two conditions
and allow a --force flag to override this behavior. Document and test.

$ tpm2_getrandom 2000
ERROR: TPM getrandom is bounded by max hash size, which is: 48
Please lower your request (preferred) and try again or use --force (advanced)
ERROR: Unable to run ./tools/tpm2_getrandom
echo $?
1

Fixes: #1405

Signed-off-by: William Roberts <william.c.roberts@intel.com>