Use correct formatspecifier for size_t
On arm the compilation fails with `tools/misc/tpm2_certifyX509certutil.c:110:17: error: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘ssize_t {aka int}’`.
This is due to a wrong format specifier.

Signed-off-by: Peter Huewe <peter.huewe@infineon.com>