Use password based sessions if no other session types specified
For authentication with ESYS_TR_PASSWORD used by the --pwd-session (-z)
parameter, ensure we turn this off when used in conjuntion with
other authentication types, like session:, file: or pcr: as using
them all together creates conflicts.

This lets combinations like the following work:

Before:

$ sudo tpm2_nvread --pwd-session --auth=session:session.ctx 0x1500016
WARN: Reading full size of the NV index
ERROR: Cannot specify password type "session:"

After:

$ sudo tpm2_nvread --pwd-session --auth=session:session.ctx 0x1500016
WARN: Reading full size of the NV index
ERROR: Could not open path "session.ctx", due to error: "No such file or directory"

This is especially useful when --pwd-session is enabled by default
in FIPS based environments.

Addresses: #3521

Signed-off-by: Satya Jhaveri <satya.jhaveri@canonical.com>
Signed-off-by: Matthew Ruffell <matthew.ruffell@canonical.com>